apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: qbittorrent
spec:
  provider: vault
  secretObjects:
  - secretName: qbittorrent
    type: Opaque
    data: 
    - objectName: VPN_USERNAME
      key: VPN_USERNAME
    - objectName:  VPN_PASSWORD 
      key:  VPN_PASSWORD 
    - objectName: LAN_NETWORK
      key: LAN_NETWORK
  parameters:
    vaultAddress: 'http://vault.vault:8200'
    vaultKubernetesMountPath: 'k8s-vault-csi'
    roleName: qbittorrent
    objects: |
      - objectName: "VPN_USERNAME"
        secretPath: "apps-kv/data/qbittorrent/vpn"
        secretKey: "VPN_USERNAME"
      - objectName: "VPN_PASSWORD"
        secretPath: "apps-kv/data/qbittorrent/vpn"
        secretKey: "VPN_PASSWORD"
      - objectName: "LAN_NETWORK"
        secretPath: "apps-kv/data/qbittorrent/vpn"
        secretKey: "LAN_NETWORK"
